CC = g++
CFLAGS = -Wall
PROG = collisions

SRCS = main.cpp imageloader.cpp vec3f.cpp


ifeq ($(shell uname),Darwin)
	LIBS = -framework OpenGL -framework GLUT
else 
	ifeq ($(shell uname),Linux)
		LIBS = -lGL -lGLU -lglut 
	else 
		LIBS = -lglut
	endif
endif

all: $(PROG)

$(PROG):	$(SRCS)
	$(CC) $(CFLAGS) -o $(PROG) $(SRCS) $(LIBS)

clean:
	rm -f $(PROG)
